# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'api_pb.rb'

module RPC
  module DummyAPI
    class DummyService < Twirp::Service
      package 'dummy.api'
      service 'Dummy'
      rpc :Ping, PingRequest, PingResponse, :ruby_method => :ping
    end

    class DummyClient < Twirp::Client
      client_for DummyService
    end
  end
end
