# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'api_pb.rb'

module RPC
  module DummyAPI
    class DummyService < Twirp::Service
      package 'dummy.api'
      service 'Dummy'
      rpc :Ping, PingRequest, PingResponse, :ruby_method => :ping
      rpc :PingRender, PingRequest, PingResponse, :ruby_method => :ping_render
      rpc :PingTemplate, PingRequest, PingResponse, :ruby_method => :ping_template
      rpc :ErrorResponse, PingRequest, PingResponse, :ruby_method => :error_response
      rpc :RaiseError, PingRequest, PingResponse, :ruby_method => :raise_error
      rpc :UncaughtError, PingRequest, PingResponse, :ruby_method => :uncaught_error
      rpc :BeforeError, PingRequest, PingResponse, :ruby_method => :before_error
    end

    class DummyClient < Twirp::Client
      client_for DummyService
    end
  end
end
