name: Ruby Test
on: push

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} (${{ matrix.gemfile }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        gemfile: [ "rails_6_1", "rails_7_0", "rails_7_2"]
        exclude:
          - ruby: "3.0"
            gemfile: "rails_7_2"
        experimental: [false]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

      - name: Run tests
        run: bin/test

      - name: Run standardrb
        run: bundle exec standardrb
